<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nmp</string>
		<string>nmpinc</string>
	</array>
	<key>name</key>
	<string>nmp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.triple.nmp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>single quotes</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.nmp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>double quotes</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.nmp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\.\w+?\(</string>
			<key>comment</key>
			<false/>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>support.function.nmp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#self</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.nmp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>support.other.nmp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'|`</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.nmp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>support.other.nmp</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>;{2,}.*$</string>
			<key>name</key>
			<string>comment.line.nmp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(#@</string>
			<key>end</key>
			<string>#\)</string>
			<key>name</key>
			<string>comment.block.nmp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nmp</string>
	<key>uuid</key>
	<string>a400b095-4742-41f3-b8d2-7039fcc6ec10</string>
</dict>
</plist>
